/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models Info */
        get: operations["models_info_api_v2_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analyses */
        get: operations["list_analyses_api_v2_analyses_get"];
        put?: never;
        /**
         * Create Analysis
         * @description Upload audio (multipart ``file`` + optional ``options`` JSON) and start an analysis.
         */
        post: operations["create_analysis_api_v2_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_api_v2_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        /** Delete Analysis */
        delete: operations["delete_analysis_api_v2_analyses__analysis_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/analyses/{analysis_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_api_v2_analyses__analysis_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/analyses/{analysis_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Server-Sent Events: ``snapshot`` first, then ``progress``/``partial`` and a final
         *     ``completed``/``failed``/``cancelled``. Resumable with ``Last-Event-ID``.
         */
        get: operations["stream_events_api_v2_analyses__analysis_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/analyses/{analysis_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_v2_analyses__analysis_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/analyses/{analysis_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Correction
         * @description Store a user's chord fix. Used for training only with ``consent_for_training``.
         */
        post: operations["add_correction_api_v2_analyses__analysis_id__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/progressions/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Next Chords */
        post: operations["next_chords_api_v2_progressions_next_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict
         * @description One chord for a short clip (v1 shape: confidence in percent).
         */
        post: operations["predict_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict_time_stamps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict Time Stamps
         * @description One chord per user-supplied slice (v1 shape).
         */
        post: operations["predict_time_stamps_predict_time_stamps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extract_full_chroma": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Full Chroma
         * @description Chromagram PNG, rendered in memory (v1 wrote a file per request and never deleted it).
         */
        post: operations["extract_full_chroma_extract_full_chroma_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alternative */
        Alternative: {
            /** Label */
            label: string;
            /** Display */
            display: string;
            /** P */
            p: number;
        };
        /** AnalysisError */
        AnalysisError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** AnalysisResult */
        AnalysisResult: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Analysis Id */
            analysis_id: string;
            /**
             * Status
             * @default completed
             * @constant
             */
            status: "completed";
            source: components["schemas"]["Source"];
            /** Models */
            models: {
                [key: string]: string;
            };
            tempo: components["schemas"]["Tempo"];
            key: components["schemas"]["KeySummary"];
            /** Beats */
            beats: number[];
            /** Downbeats */
            downbeats: number[];
            /** Bars */
            bars: components["schemas"]["Bar"][];
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["Section"][];
            /** Chords */
            chords: components["schemas"]["ChordSegment"][];
            summary: components["schemas"]["Summary"];
        };
        /** AnalysisStatus */
        AnalysisStatus: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed" | "cancelled";
            /** Stage */
            stage?: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Filename */
            filename?: string | null;
            /** Created At */
            created_at: string;
            error?: components["schemas"]["AnalysisError"] | null;
            links: components["schemas"]["Links"];
        };
        /** Bar */
        Bar: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Chords */
            chords: string[];
        };
        /** Body_create_analysis_api_v2_analyses_post */
        Body_create_analysis_api_v2_analyses_post: {
            /** File */
            file: string;
            /** Options */
            options?: string | null;
        };
        /** Body_extract_full_chroma_extract_full_chroma_post */
        Body_extract_full_chroma_extract_full_chroma_post: {
            /** File */
            file: string;
        };
        /** Body_predict_predict_post */
        Body_predict_predict_post: {
            /** File */
            file: string;
        };
        /** Body_predict_time_stamps_predict_time_stamps_post */
        Body_predict_time_stamps_predict_time_stamps_post: {
            /** File */
            file: string;
            /** Timestamps */
            timestamps: string;
        };
        /** ChordSegment */
        ChordSegment: {
            /** Index */
            index: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Beats */
            beats?: number | null;
            /** Label */
            label: string;
            /** Display */
            display: string;
            /** Root */
            root?: string | null;
            /** Quality */
            quality?: string | null;
            /** Bass */
            bass?: string | null;
            /** Roman */
            roman?: string | null;
            /** Function */
            function?: string | null;
            /** Scale Hint */
            scale_hint?: string | null;
            /** Confidence */
            confidence: number;
            /**
             * Alternatives
             * @default []
             */
            alternatives: components["schemas"]["Alternative"][];
            /**
             * Next
             * @default []
             */
            next: components["schemas"]["Prediction"][];
            /**
             * Theory Only
             * @default []
             */
            theory_only: components["schemas"]["PriorEntry"][];
            /** Surprise */
            surprise?: number | null;
        };
        /** Correction */
        Correction: {
            /** Chord Index */
            chord_index: number;
            /** New Label */
            new_label: string;
            /** Start */
            start?: number | null;
            /** End */
            end?: number | null;
            /**
             * Consent For Training
             * @default false
             */
            consent_for_training: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KeyInfo */
        KeyInfo: {
            /** Tonic */
            tonic: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "major" | "minor" | "unknown";
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
        };
        /** KeySegment */
        KeySegment: {
            /** Tonic */
            tonic: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "major" | "minor" | "unknown";
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** KeySummary */
        KeySummary: {
            global: components["schemas"]["KeyInfo"];
            /** Segments */
            segments: components["schemas"]["KeySegment"][];
        };
        /** LegacyChordPrediction */
        LegacyChordPrediction: {
            /** Chord */
            chord: string;
            /** Confidence */
            confidence: number;
        };
        /** Links */
        Links: {
            /** Self */
            self: string;
            /** Events */
            events: string;
            /** Result */
            result: string;
        };
        /** Pattern */
        Pattern: {
            /** Roman */
            roman: string[];
            /** Name */
            name?: string | null;
            /** Count */
            count: number;
        };
        /** Prediction */
        Prediction: {
            /** Label */
            label: string;
            /** Display */
            display: string;
            /** Roman */
            roman?: string | null;
            /** P */
            p: number;
            /** Reason */
            reason: string;
            /**
             * Cache Count
             * @default 0
             */
            cache_count: number;
            /** Expected Beats */
            expected_beats?: number | null;
        };
        /** PriorEntry */
        PriorEntry: {
            /** Roman */
            roman: string | null;
            /** P */
            p: number;
        };
        /** ProgressionKey */
        ProgressionKey: {
            /** Tonic */
            tonic: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "major" | "minor" | "unknown";
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** Estimated */
            estimated: boolean;
        };
        /** ProgressionRequest */
        ProgressionRequest: {
            /**
             * Chords
             * @description Chord names ('G', 'Em', 'D7', 'C/E') or Harte labels ('G:maj')
             */
            chords: string[];
            /** Durations Beats */
            durations_beats?: number[] | null;
            /**
             * Key
             * @description e.g. 'G', 'G major', 'Em'; estimated from the chords when omitted
             */
            key?: string | null;
            /**
             * K
             * @default 3
             */
            k: number;
        };
        /** ProgressionResponse */
        ProgressionResponse: {
            key_used: components["schemas"]["ProgressionKey"];
            /** Predictions */
            predictions: components["schemas"]["Prediction"][];
            /** Theory Only */
            theory_only: components["schemas"]["PriorEntry"][];
            /** Model */
            model: string;
        };
        /** Section */
        Section: {
            /** Letter */
            letter: string;
            /** Label */
            label: string;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** Source */
        Source: {
            /** Filename */
            filename?: string | null;
            /** Title */
            title?: string | null;
            /** Artist */
            artist?: string | null;
            /** Duration */
            duration: number;
            /** Sha256 */
            sha256?: string | null;
        };
        /** Summary */
        Summary: {
            /** Unique Chords */
            unique_chords: number;
            /** Time Share */
            time_share: components["schemas"]["TimeShare"][];
            /** Patterns */
            patterns: components["schemas"]["Pattern"][];
            /** Predictability */
            predictability?: number | null;
        };
        /** Tempo */
        Tempo: {
            /** Bpm */
            bpm: number | null;
            /** Meter */
            meter: string;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
        };
        /** TimeShare */
        TimeShare: {
            /** Display */
            display: string;
            /** Seconds */
            seconds: number;
            /** Share */
            share: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    models_info_api_v2_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_analyses_api_v2_analyses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatus"][];
                };
            };
        };
    };
    create_analysis_api_v2_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_analysis_api_v2_analyses_post"];
            };
        };
        responses: {
            /** @description Cache hit: this audio was already analysed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatus"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_v2_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_analysis_api_v2_analyses__analysis_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_v2_analyses__analysis_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v2_analyses__analysis_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "last-event-id"?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_v2_analyses__analysis_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_correction_api_v2_analyses__analysis_id__corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Correction"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_chords_api_v2_progressions_next_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_predict_predict_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyChordPrediction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_time_stamps_predict_time_stamps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_predict_time_stamps_predict_time_stamps_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_full_chroma_extract_full_chroma_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_full_chroma_extract_full_chroma_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
